### ISSUE TITLE
Checkout the python implementation

### ISSUE THREAD

**Issue by 3v1n0** [angelbarrera92/tlwpa4220#2]
Sorry for opening an issue but was the faster way :)

However, I've done some work to get up and running a dirty python version of the API at https://github.com/3v1n0/TL-WPA4220-python so feel free to check that and share any findings!

**Comment by angelbarrera92** [comment]
Interesting one!!

I love python btw :)

What I wanted to do with this repo is a few things:

- go pkg (so that I can use it in another project im working on natively in golang)
- prometheus exporter (I wanted to monitor who/what are attached to the PLC and also the performance of the powerline)
- cli (just because its for free)

I'll take a look to your project as it seem to have more feature implemented :)
